version: "3.7"
services:
  node:
    build: ./backend
    container_name: "youLift-backend"
    depends_on:
      - db
    networks:
      - youLift
  db:
    image: "mariadb:10.5.6"
    container_name: "youLift-bbdd"
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "false"
      MYSQL_ROOT_PASSWORD: "ZmKFxxUAPnDjXzcRyB1Jvipnp"
      MYSQL_DATABASE: "youlift"
      MYSQL_USER: "youlift"
      MYSQL_PASSWORD: "2WQdLn6yxEAJYutd8osG5QqX1"
    networks:
      - youLift
networks:
  youLift:
    name: youLift-network
